# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chucnang.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChucNang(object):
    def setupUi(self, ChucNang):
        ChucNang.setObjectName("ChucNang")
        ChucNang.resize(396, 706)
        ChucNang.setStyleSheet("QWidget#ChucNang{\n"
"border-image: url(:/newPrefix/Images/chucnang.png);\n"
"}\n"
"QPushButton{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 30px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(0, 0, 0, 20);\n"
"}")
        self.btnThongTinNguoiDung = QtWidgets.QPushButton(ChucNang)
        self.btnThongTinNguoiDung.setGeometry(QtCore.QRect(23, 101, 161, 191))
        self.btnThongTinNguoiDung.setText("")
        self.btnThongTinNguoiDung.setObjectName("btnThongTinNguoiDung")
        self.btnLenKeHoach = QtWidgets.QPushButton(ChucNang)
        self.btnLenKeHoach.setGeometry(QtCore.QRect(220, 100, 161, 191))
        self.btnLenKeHoach.setText("")
        self.btnLenKeHoach.setObjectName("btnLenKeHoach")
        self.btnLichSu = QtWidgets.QPushButton(ChucNang)
        self.btnLichSu.setGeometry(QtCore.QRect(20, 310, 161, 191))
        self.btnLichSu.setText("")
        self.btnLichSu.setObjectName("btnLichSu")
        self.btnKhamPhaMon = QtWidgets.QPushButton(ChucNang)
        self.btnKhamPhaMon.setGeometry(QtCore.QRect(210, 310, 161, 191))
        self.btnKhamPhaMon.setText("")
        self.btnKhamPhaMon.setObjectName("btnKhamPhaMon")

        self.retranslateUi(ChucNang)
        QtCore.QMetaObject.connectSlotsByName(ChucNang)

    def retranslateUi(self, ChucNang):
        _translate = QtCore.QCoreApplication.translate
        ChucNang.setWindowTitle(_translate("ChucNang", "Form"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChucNang = QtWidgets.QWidget()
    ui = Ui_ChucNang()
    ui.setupUi(ChucNang)
    ChucNang.show()
    sys.exit(app.exec_())
