# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'khamphamon.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        Form.setStyleSheet("QWidget#Form{\n"
"background: rgb(139, 233, 253);\n"
"}\n"
"QTableWidget{\n"
"border: none;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QTableWidget::item{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-bottom: 1px solid rgb(68, 71, 90);\n"
"border-left: 1px solid rgb(68, 71, 90);\n"
"color: rgb(40, 42, 48);\n"
"padding-left: 5px;\n"
"}\n"
"QTableWidget QHeaderView::section{\n"
"background-color: rgb(68, 71, 90);\n"
"border: none;\n"
"color: rgb(248, 248, 242);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"}\n"
"QTableWidget::item:selected {\n"
"background: rgba(40, 42, 54, 50);\n"
"}\n"
"QScrollBar:vertical {\n"
"border: 2px solid rgb(68, 71, 90);\n"
"background: rgb(98, 114, 164);\n"
"width: 10px;\n"
"margin: 42px 0 42px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: white;\n"
"min-height: 20px;\n"
"border-radius: 3px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"border: 2px solid rgb(68, 71, 90);\n"
"background: rgb(98, 114, 164);\n"
"height: 40px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"border: 2px solid rgb(68, 71, 90);\n"
"background: rgb(98, 114, 164);\n"
"height: 40px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"QScrollBar:horizontal {\n"
"border: 2px solid rgb(68, 71, 90);\n"
"background: rgb(98, 114, 164);\n"
"width: 10px;\n"
"margin: 42px 0 42px 0;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"background: white;\n"
"min-height: 20px;\n"
"border-radius: 3px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"border: 2px solid rgb(68, 71, 90);\n"
"background: rgb(98, 114, 164);\n"
"height: 40px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"border: 2px solid rgb(68, 71, 90);\n"
"background: rgb(98, 114, 164);\n"
"height: 40px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:vertical {\n"
"none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"QPushButton {\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(970, 730, 186, 28))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 70, 1101, 611))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Next"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "STT"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Tên"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Đạm"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Tinh bột"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Chất xơ"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Thời gian chế biến"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Calories"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Link"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
