# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lenkehoach.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LenKeHoach(object):
    def setupUi(self, LenKeHoach):
        LenKeHoach.setObjectName("LenKeHoach")
        LenKeHoach.resize(867, 722)
        LenKeHoach.setStyleSheet("QWidget#LenKeHoach{\n"
"background: rgb(139, 233, 253);\n"
"}\n"
"QCheckBox {\n"
"    spacing: 5px;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"QRadioButton {\n"
"    spacing: 5px;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"QGroupBox {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #E0E0E0, stop: 1 #FFFFFF);\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    font: 75 16pt \"MS Shell Dlg 2\";\n"
"    margin-top: 1ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center; /* position at the top center */\n"
"    padding: 0 3px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FF0ECE, stop: 1 #FFFFFF);\n"
"}\n"
"QTextEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background: yellow;\n"
"    selection-background-color: darkgray;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton {\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}")
        self.label = QtWidgets.QLabel(LenKeHoach)
        self.label.setGeometry(QtCore.QRect(0, 0, 861, 101))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(LenKeHoach)
        self.groupBox.setGeometry(QtCore.QRect(50, 160, 431, 171))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 390, 125))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxThitBo = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxThitBo.setObjectName("checkBoxThitBo")
        self.gridLayout.addWidget(self.checkBoxThitBo, 1, 0, 1, 1)
        self.checkBoxHaiSanTomMuc = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxHaiSanTomMuc.setObjectName("checkBoxHaiSanTomMuc")
        self.gridLayout.addWidget(self.checkBoxHaiSanTomMuc, 1, 1, 1, 1)
        self.checkBoxCa = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxCa.setObjectName("checkBoxCa")
        self.gridLayout.addWidget(self.checkBoxCa, 3, 0, 1, 1)
        self.checkBoxTrung = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxTrung.setObjectName("checkBoxTrung")
        self.gridLayout.addWidget(self.checkBoxTrung, 0, 1, 1, 1)
        self.checkBoxThitGaVit = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxThitGaVit.setObjectName("checkBoxThitGaVit")
        self.gridLayout.addWidget(self.checkBoxThitGaVit, 2, 0, 1, 1)
        self.checkBoxThitHeo = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxThitHeo.setObjectName("checkBoxThitHeo")
        self.gridLayout.addWidget(self.checkBoxThitHeo, 0, 0, 1, 1)
        self.checkBoxDamThucVatTauHuSuonChay = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxDamThucVatTauHuSuonChay.setObjectName("checkBoxDamThucVatTauHuSuonChay")
        self.gridLayout.addWidget(self.checkBoxDamThucVatTauHuSuonChay, 3, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(LenKeHoach)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 160, 301, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 281, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBoxBunHuTieuMien = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxBunHuTieuMien.setObjectName("checkBoxBunHuTieuMien")
        self.gridLayout_2.addWidget(self.checkBoxBunHuTieuMien, 1, 0, 1, 1)
        self.checkBoxBanhMi = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxBanhMi.setObjectName("checkBoxBanhMi")
        self.gridLayout_2.addWidget(self.checkBoxBanhMi, 2, 0, 1, 1)
        self.checkBoxComXoi = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxComXoi.setObjectName("checkBoxComXoi")
        self.gridLayout_2.addWidget(self.checkBoxComXoi, 0, 0, 1, 1)
        self.checkBoxMi = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxMi.setObjectName("checkBoxMi")
        self.gridLayout_2.addWidget(self.checkBoxMi, 3, 0, 1, 1)
        self.checkBoxChao = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxChao.setObjectName("checkBoxChao")
        self.gridLayout_2.addWidget(self.checkBoxChao, 0, 1, 1, 1)
        self.checkBoxNui = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxNui.setObjectName("checkBoxNui")
        self.gridLayout_2.addWidget(self.checkBoxNui, 1, 1, 1, 1)
        self.checkBoxBanhPho = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxBanhPho.setObjectName("checkBoxBanhPho")
        self.gridLayout_2.addWidget(self.checkBoxBanhPho, 2, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(LenKeHoach)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 350, 431, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 38, 391, 111))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBoxDuaLeoCaChua = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBoxDuaLeoCaChua.setObjectName("checkBoxDuaLeoCaChua")
        self.gridLayout_3.addWidget(self.checkBoxDuaLeoCaChua, 0, 0, 1, 1)
        self.checkBoxCaRotKhoaiTay = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBoxCaRotKhoaiTay.setObjectName("checkBoxCaRotKhoaiTay")
        self.gridLayout_3.addWidget(self.checkBoxCaRotKhoaiTay, 1, 0, 1, 1)
        self.checkBoxRauCai = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBoxRauCai.setObjectName("checkBoxRauCai")
        self.gridLayout_3.addWidget(self.checkBoxRauCai, 2, 0, 1, 1)
        self.checkBoxDau = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBoxDau.setObjectName("checkBoxDau")
        self.gridLayout_3.addWidget(self.checkBoxDau, 3, 0, 1, 1)
        self.checkBoxBi = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBoxBi.setObjectName("checkBoxBi")
        self.gridLayout_3.addWidget(self.checkBoxBi, 1, 1, 1, 1)
        self.checkBoxHanhTay = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBoxHanhTay.setObjectName("checkBoxHanhTay")
        self.gridLayout_3.addWidget(self.checkBoxHanhTay, 0, 1, 1, 1)
        self.checkBoxNam = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBoxNam.setObjectName("checkBoxNam")
        self.gridLayout_3.addWidget(self.checkBoxNam, 2, 1, 1, 1)
        self.checkBoxKhomDuaThom = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBoxKhomDuaThom.setObjectName("checkBoxKhomDuaThom")
        self.gridLayout_3.addWidget(self.checkBoxKhomDuaThom, 3, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(LenKeHoach)
        self.groupBox_4.setGeometry(QtCore.QRect(520, 350, 301, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(39, 39, 231, 101))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioNhoHon15p = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioNhoHon15p.setChecked(True)
        self.radioNhoHon15p.setObjectName("radioNhoHon15p")
        self.gridLayout_4.addWidget(self.radioNhoHon15p, 0, 0, 1, 1)
        self.radioNhoHon45p = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioNhoHon45p.setObjectName("radioNhoHon45p")
        self.gridLayout_4.addWidget(self.radioNhoHon45p, 1, 0, 1, 1)
        self.radioNhoHon30p = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioNhoHon30p.setObjectName("radioNhoHon30p")
        self.gridLayout_4.addWidget(self.radioNhoHon30p, 0, 1, 1, 1)
        self.radioLonHon45p = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.radioLonHon45p.setObjectName("radioLonHon45p")
        self.gridLayout_4.addWidget(self.radioLonHon45p, 1, 1, 1, 1)
        self.btnLenKeHoach = QtWidgets.QPushButton(LenKeHoach)
        self.btnLenKeHoach.setGeometry(QtCore.QRect(420, 540, 186, 41))
        self.btnLenKeHoach.setObjectName("btnLenKeHoach")
        self.btnNext = QtWidgets.QPushButton(LenKeHoach)
        self.btnNext.setGeometry(QtCore.QRect(630, 540, 186, 41))
        self.btnNext.setObjectName("btnNext")
        self.txtThucDon = QtWidgets.QTextEdit(LenKeHoach)
        self.txtThucDon.setGeometry(QtCore.QRect(50, 590, 771, 87))
        self.txtThucDon.setObjectName("txtThucDon")

        self.retranslateUi(LenKeHoach)
        QtCore.QMetaObject.connectSlotsByName(LenKeHoach)

    def retranslateUi(self, LenKeHoach):
        _translate = QtCore.QCoreApplication.translate
        LenKeHoach.setWindowTitle(_translate("LenKeHoach", "Form"))
        self.label.setText(_translate("LenKeHoach", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">LÊN KẾ HOẠCH</span></p></body></html>"))
        self.groupBox.setTitle(_translate("LenKeHoach", "Đạm"))
        self.checkBoxThitBo.setText(_translate("LenKeHoach", "Thịt bò"))
        self.checkBoxHaiSanTomMuc.setText(_translate("LenKeHoach", "Hải sản (Tôm, mực,…)"))
        self.checkBoxCa.setText(_translate("LenKeHoach", "Cá"))
        self.checkBoxTrung.setText(_translate("LenKeHoach", "Trứng"))
        self.checkBoxThitGaVit.setText(_translate("LenKeHoach", "Thịt gà, vịt"))
        self.checkBoxThitHeo.setText(_translate("LenKeHoach", "Thịt heo"))
        self.checkBoxDamThucVatTauHuSuonChay.setText(_translate("LenKeHoach", "Đạm thực vật (Tàu hủ, sườn chay,…)"))
        self.groupBox_2.setTitle(_translate("LenKeHoach", "Tinh bột"))
        self.checkBoxBunHuTieuMien.setText(_translate("LenKeHoach", "Bún, hủ tiếu, miến,…"))
        self.checkBoxBanhMi.setText(_translate("LenKeHoach", "Bánh mì"))
        self.checkBoxComXoi.setText(_translate("LenKeHoach", "Cơm, xôi"))
        self.checkBoxMi.setText(_translate("LenKeHoach", "Mì"))
        self.checkBoxChao.setText(_translate("LenKeHoach", "Cháo"))
        self.checkBoxNui.setText(_translate("LenKeHoach", "Nui"))
        self.checkBoxBanhPho.setText(_translate("LenKeHoach", "Bánh phở"))
        self.groupBox_3.setTitle(_translate("LenKeHoach", "Chất xơ"))
        self.checkBoxDuaLeoCaChua.setText(_translate("LenKeHoach", "Dưa leo, cà chua"))
        self.checkBoxCaRotKhoaiTay.setText(_translate("LenKeHoach", "Cà rốt, khoai tây"))
        self.checkBoxRauCai.setText(_translate("LenKeHoach", "Rau, cải"))
        self.checkBoxDau.setText(_translate("LenKeHoach", "Đậu"))
        self.checkBoxBi.setText(_translate("LenKeHoach", "Bí"))
        self.checkBoxHanhTay.setText(_translate("LenKeHoach", "Hành tây"))
        self.checkBoxNam.setText(_translate("LenKeHoach", "Nấm"))
        self.checkBoxKhomDuaThom.setText(_translate("LenKeHoach", "Khóm - Dứa - Thơm"))
        self.groupBox_4.setTitle(_translate("LenKeHoach", "Thời gian chế biến"))
        self.radioNhoHon15p.setText(_translate("LenKeHoach", "<15p"))
        self.radioNhoHon45p.setText(_translate("LenKeHoach", "<45p"))
        self.radioNhoHon30p.setText(_translate("LenKeHoach", "<30p"))
        self.radioLonHon45p.setText(_translate("LenKeHoach", ">45p"))
        self.btnLenKeHoach.setText(_translate("LenKeHoach", "Lên kế hoạch"))
        self.btnNext.setText(_translate("LenKeHoach", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LenKeHoach = QtWidgets.QWidget()
    ui = Ui_LenKeHoach()
    ui.setupUi(LenKeHoach)
    LenKeHoach.show()
    sys.exit(app.exec_())
