# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modau.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoDau(object):
    def setupUi(self, MoDau):
        MoDau.setObjectName("MoDau")
        MoDau.resize(1081, 746)
        MoDau.setStyleSheet("QWidget#MoDau{\n"
"border-image: url(:/newPrefix/Images/main.png);\n"
"}\n"
"QPushButton{\n"
"background-color: rgba(0,0,0,50);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(0,0,0,30);\n"
"}")
        self.btnNext = QtWidgets.QPushButton(MoDau)
        self.btnNext.setGeometry(QtCore.QRect(480, 590, 161, 41))
        self.btnNext.setText("")
        self.btnNext.setObjectName("btnNext")

        self.retranslateUi(MoDau)
        QtCore.QMetaObject.connectSlotsByName(MoDau)

    def retranslateUi(self, MoDau):
        _translate = QtCore.QCoreApplication.translate
        MoDau.setWindowTitle(_translate("MoDau", "Form"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MoDau = QtWidgets.QWidget()
    ui = Ui_MoDau()
    ui.setupUi(MoDau)
    MoDau.show()
    sys.exit(app.exec_())
