# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thongtinnguoidung.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThongTinNguoiDung(object):
    def setupUi(self, ThongTinNguoiDung):
        ThongTinNguoiDung.setObjectName("ThongTinNguoiDung")
        ThongTinNguoiDung.resize(416, 736)
        ThongTinNguoiDung.setStyleSheet("QWidget#ThongTinNguoiDung{\n"
"border-image: url(:/newPrefix/Images/thongtinnguoidung.png);\n"
"}\n"
"QLineEdit {\n"
"border:none;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border-bottom: 2px solid rgb(255, 184, 108);\n"
"    \n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QComboBox {\n"
"border:none;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border-bottom: 2px solid rgb(255, 184, 108);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QSpinBox {\n"
"border:none;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border-bottom: 2px solid rgb(255, 184, 108);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QDoubleSpinBox {\n"
"border:none;\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border-bottom: 2px solid rgb(255, 184, 108);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QLabel{\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgba(0,0,0,0);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(0,0,0,20);\n"
"}")
        self.label = QtWidgets.QLabel(ThongTinNguoiDung)
        self.label.setGeometry(QtCore.QRect(40, 280, 55, 16))
        self.label.setObjectName("label")
        self.txtTen = QtWidgets.QLineEdit(ThongTinNguoiDung)
        self.txtTen.setGeometry(QtCore.QRect(140, 270, 231, 22))
        self.txtTen.setObjectName("txtTen")
        self.label_2 = QtWidgets.QLabel(ThongTinNguoiDung)
        self.label_2.setGeometry(QtCore.QRect(40, 320, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ThongTinNguoiDung)
        self.label_3.setGeometry(QtCore.QRect(40, 350, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ThongTinNguoiDung)
        self.label_4.setGeometry(QtCore.QRect(40, 400, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ThongTinNguoiDung)
        self.label_5.setGeometry(QtCore.QRect(40, 440, 81, 16))
        self.label_5.setObjectName("label_5")
        self.spinBoxTuoi = QtWidgets.QSpinBox(ThongTinNguoiDung)
        self.spinBoxTuoi.setGeometry(QtCore.QRect(140, 350, 231, 22))
        self.spinBoxTuoi.setMinimum(1)
        self.spinBoxTuoi.setMaximum(100)
        self.spinBoxTuoi.setProperty("value", 18)
        self.spinBoxTuoi.setObjectName("spinBoxTuoi")
        self.comboBoxGioiTinh = QtWidgets.QComboBox(ThongTinNguoiDung)
        self.comboBoxGioiTinh.setGeometry(QtCore.QRect(140, 310, 231, 22))
        self.comboBoxGioiTinh.setObjectName("comboBoxGioiTinh")
        self.comboBoxGioiTinh.addItem("")
        self.comboBoxGioiTinh.addItem("")
        self.spinBoxCanNang = QtWidgets.QSpinBox(ThongTinNguoiDung)
        self.spinBoxCanNang.setGeometry(QtCore.QRect(140, 440, 71, 22))
        self.spinBoxCanNang.setMinimum(30)
        self.spinBoxCanNang.setMaximum(200)
        self.spinBoxCanNang.setProperty("value", 70)
        self.spinBoxCanNang.setObjectName("spinBoxCanNang")
        self.label_6 = QtWidgets.QLabel(ThongTinNguoiDung)
        self.label_6.setGeometry(QtCore.QRect(210, 390, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(ThongTinNguoiDung)
        self.label_7.setGeometry(QtCore.QRect(220, 440, 81, 21))
        self.label_7.setObjectName("label_7")
        self.spinBoxChieuCao = QtWidgets.QSpinBox(ThongTinNguoiDung)
        self.spinBoxChieuCao.setGeometry(QtCore.QRect(140, 400, 61, 22))
        self.spinBoxChieuCao.setMinimum(1)
        self.spinBoxChieuCao.setMaximum(250)
        self.spinBoxChieuCao.setProperty("value", 170)
        self.spinBoxChieuCao.setObjectName("spinBoxChieuCao")
        self.btnNext = QtWidgets.QPushButton(ThongTinNguoiDung)
        self.btnNext.setGeometry(QtCore.QRect(160, 580, 101, 41))
        self.btnNext.setText("")
        self.btnNext.setObjectName("btnNext")
        self.label_8 = QtWidgets.QLabel(ThongTinNguoiDung)
        self.label_8.setGeometry(QtCore.QRect(40, 490, 191, 41))
        self.label_8.setObjectName("label_8")
        self.labelTongLuongCalo = QtWidgets.QLabel(ThongTinNguoiDung)
        self.labelTongLuongCalo.setGeometry(QtCore.QRect(274, 500, 61, 20))
        self.labelTongLuongCalo.setObjectName("labelTongLuongCalo")

        self.retranslateUi(ThongTinNguoiDung)
        QtCore.QMetaObject.connectSlotsByName(ThongTinNguoiDung)

    def retranslateUi(self, ThongTinNguoiDung):
        _translate = QtCore.QCoreApplication.translate
        ThongTinNguoiDung.setWindowTitle(_translate("ThongTinNguoiDung", "Form"))
        self.label.setText(_translate("ThongTinNguoiDung", "Tên"))
        self.label_2.setText(_translate("ThongTinNguoiDung", "Giới tính"))
        self.label_3.setText(_translate("ThongTinNguoiDung", "Tuổi"))
        self.label_4.setText(_translate("ThongTinNguoiDung", "Chiều cao"))
        self.label_5.setText(_translate("ThongTinNguoiDung", "Cân nặng"))
        self.comboBoxGioiTinh.setItemText(0, _translate("ThongTinNguoiDung", "Nam"))
        self.comboBoxGioiTinh.setItemText(1, _translate("ThongTinNguoiDung", "Nữ"))
        self.label_6.setText(_translate("ThongTinNguoiDung", "(cm)"))
        self.label_7.setText(_translate("ThongTinNguoiDung", "(kg)"))
        self.label_8.setText(_translate("ThongTinNguoiDung", "Tổng lượng calo tiêu thụ: "))
        self.labelTongLuongCalo.setText(_translate("ThongTinNguoiDung", "0"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ThongTinNguoiDung = QtWidgets.QWidget()
    ui = Ui_ThongTinNguoiDung()
    ui.setupUi(ThongTinNguoiDung)
    ThongTinNguoiDung.show()
    sys.exit(app.exec_())
